### ISSUE TITLE
Feature Request : False Positive Detection Improvement

### ISSUE THREAD

**Issue by chgg-kboberg** [lapt0r/goose#12]
**Is your feature request related to a problem? Please describe.**
Output of Goose does not correctly discard things like "reflected" content (password = "password", api_token = configuration.foo.api_token, etc)

**Describe the solution you'd like**
As part of Goose's stated goals, these should be filtered out, drastically lowering the false positive rate.

The previous incarnation of this tool used a multitude of "sieves" based on common false positive criteria.  Additionally, the latent entropy engine could be applied to the matched value.

**Describe alternatives you've considered**
Tightening the regex **could** work but would result in additional scan time complexity.  Over large targets, this would make the application catastrophically slow.

**Additional context**
N/A

**Comment by hackimed3s** [comment]
Cool. I'll take this on later this week.
