### ISSUE TITLE
Piping to a file in powershell adds the EOL tag, making JSON not valid

### ISSUE THREAD

**Issue by hackimed3s** [lapt0r/goose#19]
In Powershell if you run:
``` go run .\goose.go -target C:\Users\morgansasus\go\src\goose  > output.json; get-content output.json -raw | convertfrom-json```
it will fail since the json is invalid.
Example:
`
Error reading file [C:\Users\morgansasus\go\src\goose\o.json] : EOF[{"Match":"string mysupersecretpassword = \"hacktheplanet1337!\"","Location":"C:\\Users\\morgansasus\\go\\src\\goose\\internal\\pkg\\loade
`

**Comment by lapt0r** [comment]
Resolved by #27
