### ISSUE TITLE
JSON output on Windows has encoding errors

### ISSUE THREAD

**Issue by lapt0r** [lapt0r/goose#6]
Goose JSON output is incorrectly formatted.

- Expected : ```"(?i)(?:\\w+)?\\s(?:\\w+)?(?:password|token|key\\s|secret)\\s(=|:|<-|:=)\\s[\"']?([a-z0-9!@#$%^&*()?,.<>;~`\\-=_]{8,})[\"']?"```
- Actual : ```"(?i)(?:\\w+)?\\s(?:\\w+)?(?:password|token|key\\s|secret)\\s(=|:|\u003c-|:=)\\s[\"']?([a-z0-9!@#$%!^(MISSING)\u0026*()?,.\u003c\u003e;~`\\-=_]{8,})[\"']?"```

This looks like it may be related to .NET's default Unicode (UTF16) encoding.

**Comment by hackimed3s** [comment]
@lapt0r mind if I take a whack at this?

**Comment by hackimed3s** [comment]
![image](https://user-images.githubusercontent.com/8112247/71797512-51955e00-3003-11ea-8f95-9ef99a09a3bc.png)
Fix is just to ensure the string doesn't interpolate

**Comment by lapt0r** [comment]
Fixed by #11
